packages:
  - 'generated/*'
  - 'packages/*'
  - 'commands/*'
  - 'apis/*'
  - 'test/component/*'
overrides:
  'caniuse-lite': '1.0.30001734'
  'react': '18.3.1'
  'react-dom': '18.3.1'
  'react-is': '18.3.1'
  '@playwright/test': '1.54.2'
