import apis from '../oxlint.apis.ts';
import { defineConfig } from 'oxlint';
import { react } from '@qlik/oxlint-config';
import { SHARED_NO_UNDERSCORE_DANGLE_ALLOW } from '../../oxlint.base.ts';

export default defineConfig({
  extends: [apis, react],
  // types/index.d.ts is auto-generated by @scriptappy/to-dts; DO NOT lint it
  ignorePatterns: ['types/**'],
  rules: { 'no-underscore-dangle': ['error', { allow: SHARED_NO_UNDERSCORE_DANGLE_ALLOW }] },
});
